services:
  master-node:
    build: ./packages/master-node/
    env_file:
      - ./packages/master-node/.env
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - WORKER_NODE_ENDPOINT=http://worker-node:8080
    depends_on:
      - worker-node
    # Define extra_hosts only if using a local prover network
    extra_hosts:
      - host.docker.internal:host-gateway

  worker-node:
    build: ./packages/worker-node/
    env_file:
      - ./packages/worker-node/.env
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    ports:
      - "8080:8080"
    # Define extra_hosts only if using a local prover network
    extra_hosts:
      - host.docker.internal:host-gateway